image: camdl/docker-compose-pipelines:1.0.1

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          script:
            - docker-compose run test
          services:
            - docker
          caches:
            - docker
      - step:
          name: Build [unpublished] camdl/cudl-services image
          script:
            - docker-compose run build
          services:
            - docker
          caches:
            - docker
definitions:
  services:
    docker:
      memory: 3072
