name: Test and publish Docker image

on: push

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit & integration tests
        run: docker-compose run --rm test
  docker-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & tag image
        id: build-docker-image
        run: make docker-image github-actions-set-docker-image-tag-outputs
      - name: Smoke test image
        env:
          SMOKE_TEST_IMAGE_VERSION: "${{ steps.build-docker-image.outputs.IMAGE_TAG_COMMIT_SHA }}"
        run: |
          docker-compose \
            -f docker-compose.yml \
            -f docker/docker-compose_image-smoke-test.yml \
            run smoke-test
